# Site settings
title: Alex Winter
description: A minimal personal site
url: https://alexwinter.me
github_url: https://github.com/sonofliberty/sonofliberty.github.io
author:
  name: Aleksander Winter
  email: aleksander.winter.89@gmail.com
  url: sonofliberty.github.io
social:
  github: sonofliberty
  linkedin: alexwinter89
  facebook: aleksander.winter.790
  email: aleksander.winter.89@gmail.com

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:year/:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      og_type: article

# Plugins
plugins:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
