# Site settings
title: Alex Winter
tag_line: Symfony / PHP web developer
description: A minimal personal site
locale: en
url: https://alexwinter.me
github_url: https://github.com/sonofliberty/sonofliberty.github.io
author:
  name: Aleksander Winter
  email: hi@alexwinter.me
  url: sonofliberty.github.io
social:
  github: sonofliberty
  linkedin: alexwinter89
  #facebook: aleksander.winter.790
  email: hi@alexwinter.me

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:categories/:slug
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      og_type: article

# Plugins
plugins:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
