# Site settings
title: Alex Winter
description: A minimal personal site
url: "http://www.jacoporabolini.com/emerald"
author:
  name: Aleksander Winter
  email: aleksander.winter.89@gmail.com
  url: sonofliberty.github.io

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
