version: '3'

services:

  web1:
    image: tutum/hello-world
    environment:
      - VIRTUAL_HOST=web1.local

  web2:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=web2.local

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro